<a href="https://colab.research.google.com/github/Niteshsinghbisht03/Pytorch/blob/main/Manual_Pytorch_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **important Libraries**

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# **Data Loading and Preprocessing**

In [4]:
#data loading
df = pd.read_csv("/content/breast-cancer.csv")

In [5]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [6]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [7]:
df.shape

(569, 32)

In [8]:
df.drop(columns=['id'],inplace=True)

In [9]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [10]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,shuffle=True)

# **Train_Test Split**

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_test

array([[ 0.05986724, -0.27177152, -0.01249657, ..., -0.6101971 ,
        -0.43356359, -0.42418404],
       [-0.91244669, -1.62605196, -0.94026455, ..., -1.26968925,
        -1.21668301, -0.99959296],
       [ 0.06857453, -0.58590874, -0.05115357, ..., -1.24854778,
        -0.71631259, -1.2909181 ],
       ...,
       [-0.68025232, -0.62081287, -0.70580145, ..., -0.69567556,
        -1.90131682, -0.60967404],
       [-1.69349051,  0.31694489, -1.60709779, ..., -0.55711529,
         0.65613199,  3.57749815],
       [ 1.58944766, -0.10190473,  1.59597074, ...,  1.25603181,
         0.09381094,  0.83079786]])

In [13]:
y_test.unique()

array(['B', 'M'], dtype=object)

In [14]:
le=LabelEncoder()


In [15]:
y_test=le.fit_transform(y_test)
y_train=le.transform(y_train)

In [16]:
y_test.shape

(114,)

In [17]:
X_train.shape

(455, 30)

# **Numpy array to Torch Tensor**

In [29]:
X_test_tensor=torch.from_numpy(X_test)
X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [30]:
X_test.shape

(114, 30)

In [31]:
y_test.shape

(114,)

# **Defining a Model**

In [32]:
class mySimpleNN():
  #initialize the weights and bias
  def __init__(self,X):
    self.w=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
    self.b=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  #Feed Forward Training
  def forward_pass(self,X):
    return torch.sigmoid(torch.matmul(X,self.w)+self.b)

  #loss calculation
  def loss(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    return -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()




# **Important Parameters**

In [33]:
#Learning Rate and number of Epochs
lr=0.1
epochs=300

# **Training Pipeline**

In [41]:
#create Model
model = mySimpleNN(X_train_tensor)

for epochs in range(epochs):
  #forward Prediciton
  y_pred = model.forward_pass(X_train_tensor)

  #loss calculation
  loss= model.loss(y_pred,y_train_tensor)

  #backpropogation
  loss.backward()

  #weight updation
  with torch.no_grad():
    model.w -= lr * model.w.grad
    model.b -= lr * model.b.grad


  model.w.grad.zero_()
  model.b.grad.zero_()

  print(f'epochs: {epochs+1 }  :  loss: {loss.item()}')


epochs: 1  :  loss: 3.8296637358189014
epochs: 2  :  loss: 3.7144526237964555
epochs: 3  :  loss: 3.5951723731499787
epochs: 4  :  loss: 3.469478312849275
epochs: 5  :  loss: 3.339257244807076
epochs: 6  :  loss: 3.205182338717596
epochs: 7  :  loss: 3.0678867560300374
epochs: 8  :  loss: 2.9275393761901043
epochs: 9  :  loss: 2.7868457577560592
epochs: 10  :  loss: 2.644346722185834
epochs: 11  :  loss: 2.500200749305724
epochs: 12  :  loss: 2.3576100532318014
epochs: 13  :  loss: 2.2145676226056783
epochs: 14  :  loss: 2.074045053253567
epochs: 15  :  loss: 1.9377905880144368
epochs: 16  :  loss: 1.8027888796876417
epochs: 17  :  loss: 1.673189468493516
epochs: 18  :  loss: 1.552544540841221
epochs: 19  :  loss: 1.4395115556805487
epochs: 20  :  loss: 1.3368304685523642
epochs: 21  :  loss: 1.2473137959514593
epochs: 22  :  loss: 1.1708729066854042
epochs: 23  :  loss: 1.106759478655423
epochs: 24  :  loss: 1.0536215195776788
epochs: 25  :  loss: 1.0097480008455735
epochs: 26  :  los

In [35]:
y_pred.shape

torch.Size([455, 1])

In [36]:
print(loss)

tensor(0.6654, dtype=torch.float64, grad_fn=<NegBackward0>)


In [37]:
model.w

tensor([[ 0.1619],
        [ 0.1709],
        [ 0.0280],
        [-0.2805],
        [-0.0410],
        [-0.2056],
        [-0.1784],
        [ 0.0965],
        [ 0.0563],
        [ 0.0284],
        [-0.1097],
        [ 0.0879],
        [-0.0652],
        [ 0.1106],
        [-0.0242],
        [-0.0530],
        [ 0.0563],
        [ 0.0279],
        [ 0.1078],
        [-0.0395],
        [-0.0673],
        [-0.2615],
        [-0.0247],
        [ 0.3297],
        [ 0.1107],
        [ 0.2797],
        [ 0.0808],
        [-0.0972],
        [-0.1408],
        [-0.0013]], dtype=torch.float64, requires_grad=True)

In [38]:
y_pred

tensor([[0.4212],
        [0.3603],
        [0.3416],
        [0.3635],
        [0.3958],
        [0.4326],
        [0.3546],
        [0.3520],
        [0.3544],
        [0.4122],
        [0.3795],
        [0.3696],
        [0.3603],
        [0.3683],
        [0.3581],
        [0.4753],
        [0.3638],
        [0.3676],
        [0.4018],
        [0.3604],
        [0.3793],
        [0.4055],
        [0.3600],
        [0.3642],
        [0.3744],
        [0.3869],
        [0.3822],
        [0.4136],
        [0.3384],
        [0.3618],
        [0.3803],
        [0.3681],
        [0.3785],
        [0.4057],
        [0.3839],
        [0.3468],
        [0.4057],
        [0.3636],
        [0.3551],
        [0.3979],
        [0.4157],
        [0.4029],
        [0.3692],
        [0.3753],
        [0.3768],
        [0.3685],
        [0.3590],
        [0.4524],
        [0.4005],
        [0.3376],
        [0.3818],
        [0.3535],
        [0.3646],
        [0.3527],
        [0.4212],
        [0

In [39]:
#Accuracy metrics
with torch.no_grad():
  y_pred=model.forward_pass(X_test_tensor)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred==y_test_tensor).float().mean()
  print(f'{accuracy.item()}')

0.6465066075325012
