<a href="https://colab.research.google.com/github/Niteshsinghbisht03/Pytorch/blob/main/Manual_Pytorch_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **important Libraries**

In [67]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [68]:
import torch.nn as nn

# **Data Loading and Preprocessing**

In [69]:
#data loading
df = pd.read_csv("/content/breast-cancer.csv")

In [70]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [71]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [72]:
df.shape

(569, 32)

In [73]:
df.drop(columns=['id'],inplace=True)

In [74]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [75]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,shuffle=True)

# **Train_Test Split**

In [76]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [77]:
X_test

array([[-0.46325571, -0.28716378, -0.5299657 , ..., -1.50444904,
        -1.08990574, -1.66709962],
       [-0.8053837 ,  0.44650377, -0.81703341, ..., -0.4931421 ,
        -0.11548396,  0.25951909],
       [ 0.11836187, -1.30141892,  0.0851203 , ..., -0.35491138,
        -0.44737594, -0.77856239],
       ...,
       [ 0.70853266,  0.47410255,  0.73495224, ...,  1.43599857,
         1.16630575,  0.68545835],
       [ 1.93164022,  0.97548037,  1.93037829, ...,  1.45122221,
         0.37009199, -0.31247311],
       [ 0.02712774,  0.07622015,  0.23154965, ...,  0.53780334,
        -0.82014132,  1.41630496]])

In [78]:
y_test.unique()

array(['B', 'M'], dtype=object)

In [79]:
le=LabelEncoder()


In [80]:
y_test=le.fit_transform(y_test)
y_train=le.transform(y_train)

In [81]:
y_test.shape

(114,)

In [82]:
X_train.shape

(455, 30)

# **Numpy array to Torch Tensor**

In [83]:
X_test_tensor=torch.from_numpy(X_test)
X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [84]:
X_test.shape

(114, 30)

In [85]:
y_test.shape

(114,)

# **Defining a Model**

In [90]:
class mySimpleNN():
  #initialize the weights and bias
  def __init__(self,X):
    self.w=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.double)
    self.b=torch.zeros(1,dtype=torch.double,requires_grad=True)

  #Feed Forward Training
  def forward_pass(self,X):
    return torch.sigmoid(torch.matmul(X,self.w)+self.b)

  #loss calculation
  def loss(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    return -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()




In [87]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out=self.sigmoid(out)
    return out


# **Important Parameters**

In [88]:
#Learning Rate and number of Epochs
lr=0.1
epochs=300

# **Training Pipeline**

In [91]:
#create Model
model = mySimpleNN(X_train_tensor)

for epochs in range(epochs):
  #forward Prediciton
  y_pred = model.forward_pass(X_train_tensor)

  #loss calculation
  loss= model.loss(y_pred,y_train_tensor)

  #backpropogation
  loss.backward()

  #weight updation
  with torch.no_grad():
    model.w -= lr * model.w.grad
    model.b -= lr * model.b.grad


  model.w.grad.zero_()
  model.b.grad.zero_()

  print(f'epochs: {epochs+1 }  :  loss: {loss.item()}')


epochs: 1  :  loss: 3.6424174649012375
epochs: 2  :  loss: 3.5181686560262313
epochs: 3  :  loss: 3.389347756352007
epochs: 4  :  loss: 3.2538772401895386
epochs: 5  :  loss: 3.1104800447346257
epochs: 6  :  loss: 2.9656033461959397
epochs: 7  :  loss: 2.81759347459067
epochs: 8  :  loss: 2.666118347517232
epochs: 9  :  loss: 2.507947949124806
epochs: 10  :  loss: 2.3488243767091648
epochs: 11  :  loss: 2.1880422454797746
epochs: 12  :  loss: 2.030318458519163
epochs: 13  :  loss: 1.878425581572935
epochs: 14  :  loss: 1.7282080615863338
epochs: 15  :  loss: 1.5860938836313727
epochs: 16  :  loss: 1.4511814700770629
epochs: 17  :  loss: 1.324110735977669
epochs: 18  :  loss: 1.2122955465848648
epochs: 19  :  loss: 1.1166107078863712
epochs: 20  :  loss: 1.0370145672501696
epochs: 21  :  loss: 0.9724576017062928
epochs: 22  :  loss: 0.92107041232092
epochs: 23  :  loss: 0.880549644087548
epochs: 24  :  loss: 0.8485869974701427
epochs: 25  :  loss: 0.8231674806276496
epochs: 26  :  loss:

In [92]:
#Pytorch Based Code
model2 = Model(X_train_tensor.shape[1])

In [101]:
loss_function = nn.BCELoss()

In [107]:
X_train_tensor = X_train_tensor.type(torch.float32)

optimizer = torch.optim.SGD(model2.parameters(),lr=lr)

for epochs in range(epochs):
  #forward Prediciton
  y_pred = model2(X_train_tensor)

  #loss calculation
  loss= loss_function(y_pred,y_train_tensor.view(-1,1))

  #clear gradient
  optimizer.zero_grad()

  #backpropogation
  loss.backward()

  #weight updation
  optimizer.step()


  print(f'epochs: {epochs+1 }  :  loss: {loss.item()}')



In [108]:
y_pred.shape

torch.Size([114, 1])

In [109]:
print(loss)

tensor(0.6644, dtype=torch.float64, grad_fn=<NegBackward0>)


In [110]:
model2.linear.weight

Parameter containing:
tensor([[ 0.1618,  0.0620,  0.0899,  0.1202,  0.0810, -0.1380,  0.0854,  0.1686,
         -0.0981, -0.0953, -0.1206,  0.1264,  0.1361,  0.0624,  0.1303,  0.0465,
          0.0696, -0.0337,  0.0388, -0.1688,  0.0446, -0.1031,  0.1692, -0.1579,
         -0.1816,  0.1546, -0.0688, -0.1037, -0.1571,  0.1770]],
       requires_grad=True)

In [111]:
y_pred

tensor([[1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
      

In [112]:
#Accuracy metrics for custom pipeline
with torch.no_grad():
  y_pred=model.forward_pass(X_test_tensor)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred==y_test_tensor).float().mean()
  print(f'{accuracy.item()}')

0.640350878238678


In [113]:
#Accuracy metrics for Torch pipeline Model
with torch.no_grad():
  y_pred=model2.forward(X_test_tensor.type(model2.linear.weight.dtype))
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred==y_test_tensor).float().mean()
  print(f'{accuracy.item()}')

0.4827639162540436
