<a href="https://colab.research.google.com/github/Niteshsinghbisht03/Pytorch/blob/main/Neural_Network_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# **Creating a Network with a Single Perceptron**

In [2]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__() #invoke parent class constructor
    self.linear = nn.Linear(num_features,1)  #only one layer in Network -> Parameters = (total number of columns in data,output number)


  def forward(self,features):
    out = self.linear(features) #calculating wx+b
    out = torch.sigmoid(out) #claculating sigmoid(z)

    return out

In [3]:
features = torch.rand(10,5) #creating a random dataset

In [4]:
features

tensor([[0.4463, 0.0917, 0.2978, 0.7380, 0.4758],
        [0.2761, 0.2800, 0.0012, 0.4324, 0.8009],
        [0.9296, 0.2621, 0.6277, 0.3718, 0.0483],
        [0.6864, 0.8672, 0.3932, 0.1563, 0.2778],
        [0.5567, 0.8969, 0.7076, 0.2441, 0.6008],
        [0.6143, 0.3927, 0.0601, 0.0943, 0.8326],
        [0.0030, 0.2091, 0.5885, 0.7408, 0.0624],
        [0.9821, 0.4084, 0.9536, 0.8085, 0.9338],
        [0.1950, 0.5906, 0.9959, 0.1344, 0.5749],
        [0.4189, 0.1499, 0.2038, 0.5581, 0.8931]])

In [5]:
#create a object of Model
model = Model(features.shape[1])

In [6]:
#call model for Forward Pass
model(features)

tensor([[0.5788],
        [0.5117],
        [0.6884],
        [0.6748],
        [0.6677],
        [0.5430],
        [0.6150],
        [0.6706],
        [0.6331],
        [0.5266]], grad_fn=<SigmoidBackward0>)

In [11]:
#weights of model
print(model.linear.weight)

#bias of model
print(model.linear.bias)

Parameter containing:
tensor([[ 0.3665,  0.3879,  0.3677,  0.1517, -0.3880]], requires_grad=True)
Parameter containing:
tensor([0.0817], requires_grad=True)


In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary

In [10]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Creating a Network With a Hidden Layer**

In [14]:
class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__() #invoke parent class constructor
    self.linear1 = nn.Linear(num_features,3)  #only one layer in Network -> Parameters = (total number of columns in data,output number)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features) #calculating wx+b
    out = self.relu(out) #claculating sigmoid(z)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [16]:
model2 = Model2(features.shape[1])

In [19]:
model2(features)

tensor([[0.3929],
        [0.3857],
        [0.4062],
        [0.3931],
        [0.3810],
        [0.3842],
        [0.3909],
        [0.4229],
        [0.3511],
        [0.3914]], grad_fn=<SigmoidBackward0>)

In [24]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [21]:
#weights of model
print(model2.linear1.weight)

#bias of model
print(model2.linear1.bias)

Parameter containing:
tensor([[ 0.1496,  0.0893,  0.1945,  0.1465,  0.0433],
        [ 0.3395,  0.3027, -0.2861, -0.2660,  0.1223],
        [-0.1083,  0.1531,  0.2142, -0.4107,  0.1632]], requires_grad=True)
Parameter containing:
tensor([-0.1630, -0.0651,  0.0453], requires_grad=True)


In [22]:
#weights of model
print(model2.linear2.weight)

#bias of model
print(model2.linear2.bias)

Parameter containing:
tensor([[ 0.5042,  0.2644, -0.5690]], requires_grad=True)
Parameter containing:
tensor([-0.4848], requires_grad=True)


# **Creating a Model using Sequential Container**

In [25]:
class Model3(nn.Module):
  def __init__(self,num_features):
    super().__init__() #invoke parent class constructor
    self.network = nn.Sequential(
    nn.Linear(num_features,3),  #only one layer in Network -> Parameters = (total number of columns in data,output number)
    nn.ReLU(),
    nn.Linear(3,1),
    nn.Sigmoid()
    )

  def forward(self,features):
    out  = self.network(features)

    return out

In [28]:
model3 = Model3(features.shape[1])

In [29]:
model3(features)

tensor([[0.5872],
        [0.5854],
        [0.5781],
        [0.5880],
        [0.6009],
        [0.5938],
        [0.5735],
        [0.5767],
        [0.6080],
        [0.5935]], grad_fn=<SigmoidBackward0>)

In [32]:
model3.network[0].weight

Parameter containing:
tensor([[ 0.2814,  0.3077,  0.3497,  0.2930, -0.3115],
        [-0.1365,  0.1534, -0.2799,  0.1445, -0.2124],
        [ 0.0463,  0.3568,  0.2794, -0.4295, -0.0832]], requires_grad=True)

In [34]:
model3.network[2].weight

Parameter containing:
tensor([[-0.2329, -0.3458,  0.5715]], requires_grad=True)